#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ $# -lt 3 ]]; then
  cat >&2 <<'EOF'
Usage:
  scripts/run_d2ma_sidechannel_isolated.sh DATASET_ID METHOD OUT_DIR [PROFILE]

METHOD:
  raw
  d2ma_min
  d2ma_b_r5
  d2ma_b_r5_precision_mainline
  d2ma_b_r5_static_pose_refine
  d2ma_b_r5_static_pose_refine_residual_gate
  d2ma_support_b_r5_s18_m2_o2
  d2ma_supportq_b_r5_s18_m2_o2_q2
  d2ma_supportq_lm_only_b_r5_s18_m2_o2_q2
  d2ma_supportq_lm_only_b_r5_s18_m2_o2_q2_precision
  d2ma_supportq_lm_only_sweep
  d2ma_score_lm_only_v4
  d2ma_score_lm_only_v4_precision
  d2ma_lifecycle_v8_precision
  d2ma_lifecycle_v9_precision
  d2ma_occlusion_aware_v10_precision
  d2ma_recovery_v11_precision
  d2ma_recovery_v12_probation_precision
  d2ma_recovery_v12_fixed_delay_2kf_precision
  d2ma_recovery_v12_fixed_delay_4kf_precision
  d2ma_recovery_v13_pose_chain_guard_precision
  d2ma_score_lm_only_v5
  d2ma_state_aware_lm_only_v6
  d2ma_coverage_aware_lm_only_v7
  d2ma_coverage_aware_lm_only_v7_plain
  d2ma_coverage_aware_lm_only_v7_shadow
  samecount_nonboundary_r5
  matched_nonboundary_r5

This wrapper enforces the D2MA side-channel isolation protocol:
  - masks are passed only as map-admission provenance side-channel
  - RGB/depth are not image-level filtered by ORB-SLAM3 mask mode
  - dynamic feature deletion, depth invalidation, and pose-level panoptic paths are disabled
EOF
  exit 2
fi

DATASET_ID="$1"
METHOD="$2"
OUT_DIR="$3"
PROFILE="${4:-hybrid_sequential_semantic_only}"

export DSLAM_CPUSET="${DSLAM_CPUSET:-0}"
OCCLUSION_LOG_REQUESTED="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_LOG:-0}"
RECOVERY_V11_LOG_REQUESTED="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_LOG:-0}"
RECOVERY_V11_EARLY_LBA_REQUESTED="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_EARLY_LBA:-1}"
POSE_CHAIN_GUARD_V13_LOG_REQUESTED="${STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_LOG:-0}"
LIFECYCLE_DUMP_REQUESTED="${STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP:-0}"

export ORB_SLAM3_MASK_MODE=off
export STSLAM_PANOPTIC_SIDE_CHANNEL_ONLY=1
export STSLAM_FORCE_FILTER_DETECTED_DYNAMIC_FEATURES=0
export STSLAM_FORCE_FILTER_DETECTED_DYNAMIC_FEATURE_STAGES=none
export STSLAM_RGBD_DYNAMIC_FRONTEND_SPLIT=0
export STSLAM_SEMANTIC_GEOMETRIC_VERIFICATION=0
export STSLAM_SEMANTIC_CANDIDATE_GEOMETRY_GATE=0
export STSLAM_SEMANTIC_CANDIDATE_SPARSE_FLOW_GATE=0
export STSLAM_SEMANTIC_CONSERVATIVE_DYNAMIC_DELETE=0
export STSLAM_SEMANTIC_STRICT_STATIC_KEEP=0
export STSLAM_GEOMETRIC_DYNAMIC_REJECTION=0
export STSLAM_DYNAMIC_DEPTH_INVALIDATION=0
export STSLAM_OBSERVABILITY_LOG=1

export STSLAM_DYNAMIC_MAP_ADMISSION_VETO=0
export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_STEREO_INITIALIZATION=0
export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_NEED_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0

export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_DIAGNOSTICS=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0

export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_CREATE_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL_CREATE_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0

export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY=0
export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0
export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY=0
export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED=0
export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_AWARE=0
export STSLAM_DYNAMIC_MAP_ADMISSION_COVERAGE_AWARE_V7=0
export STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION=0
export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_V8=0
export STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9=0
export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_AWARE=0
export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_AWARE_LBA_DELAY=0
export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_LOG=0
export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11=0
export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_LOG=0
export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_EARLY_LBA=0
export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_PROBATION=0
export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MODE=posterior
export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_FIXED_DELAY_KFS=2
export STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13=0
export STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_LOG=0
export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT=0
export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG=0
export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP=0
export STSLAM_DYNAMIC_MAP_ADMISSION_V5_USEFULNESS_LOG=0
export STSLAM_DYNAMIC_MAP_ADMISSION_V5_TRACE_LOG=0

export STSLAM_NEAR_BOUNDARY_DIAGNOSTICS="${STSLAM_NEAR_BOUNDARY_DIAGNOSTICS:-0}"
export STSLAM_NEAR_BOUNDARY_DIAGNOSTIC_RADIUS_PX="${STSLAM_NEAR_BOUNDARY_DIAGNOSTIC_RADIUS_PX:-5}"
export STSLAM_STATIC_BACKGROUND_POSE_REFINE=0
export STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG=0
export STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN=0
export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_TRANSLATION_M=0
export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_ROTATION_DEG=0

case "$METHOD" in
  raw)
    ;;
  d2ma_min)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    ;;
  d2ma_b_r5)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    ;;
  d2ma_b_r5_precision_mainline)
    export STSLAM_OBSERVABILITY_LOG=0
    export STSLAM_NEAR_BOUNDARY_DIAGNOSTICS=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP=0
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE=0
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG=0
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN=0
    ;;
  d2ma_b_r5_static_pose_refine)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE=1
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG=1
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_MATCHES="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_MATCHES:-80}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_NEAR_RADIUS_PX="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_NEAR_RADIUS_PX:-5}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_TRANSLATION_M="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_TRANSLATION_M:-0.05}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_ROTATION_DEG="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_ROTATION_DEG:-5.0}"
    ;;
  d2ma_b_r5_static_pose_refine_residual_gate)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE=1
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG=1
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_MATCHES="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_MATCHES:-160}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_NEAR_RADIUS_PX="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_NEAR_RADIUS_PX:-5}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_TRANSLATION_M="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_TRANSLATION_M:-0.002}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_ROTATION_DEG="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_ROTATION_DEG:-0.05}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_TRANSLATION_M=0.0005
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_ROTATION_DEG=0.01
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN=1
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_MEAN_CHI2_BEFORE="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_MEAN_CHI2_BEFORE:-3.0}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_CHI2_GAIN_RATIO="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_CHI2_GAIN_RATIO:-0.02}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_CHI2_GAIN_ABS="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_CHI2_GAIN_ABS:-0.0}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_INLIER_RATIO_GAIN="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_INLIER_RATIO_GAIN:-0.0}"
    export STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_MEAN_CHI2_AFTER="${STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_MEAN_CHI2_AFTER:-5.991}"
    ;;
  d2ma_support_b_r5_s18_m2_o2)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX=18
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS=2
    ;;
  d2ma_supportq_b_r5_s18_m2_o2_q2)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX=18
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE=0.70
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2=3.0
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO=0.35
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF=0.25
    ;;
  d2ma_supportq_lm_only_b_r5_s18_m2_o2_q2|d2ma_supportq_lm_only_b_r5_s18_m2_o2_q2_precision)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX=18
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE=0.70
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2=3.0
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO=0.35
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN=2
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF=0.25
    if [[ "$METHOD" == "d2ma_supportq_lm_only_b_r5_s18_m2_o2_q2_precision" ]]; then
      export STSLAM_OBSERVABILITY_LOG=0
      export STSLAM_NEAR_BOUNDARY_DIAGNOSTICS=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP="${LIFECYCLE_DUMP_REQUESTED:-0}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V5_USEFULNESS_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_V5_TRACE_LOG=0
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE=0
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG=0
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN=0
    fi
    ;;
  d2ma_supportq_lm_only_sweep)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX="${STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX:-5}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX:-18}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE:-0.70}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2:-3.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO:-0.35}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF:-0.25}"
    ;;
  d2ma_score_lm_only_v4|d2ma_score_lm_only_v4_precision|d2ma_lifecycle_v8_precision|d2ma_lifecycle_v9_precision|d2ma_occlusion_aware_v10_precision|d2ma_recovery_v11_precision|d2ma_recovery_v12_probation_precision|d2ma_recovery_v12_fixed_delay_2kf_precision|d2ma_recovery_v12_fixed_delay_4kf_precision|d2ma_recovery_v13_pose_chain_guard_precision)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX="${STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX:-5}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX:-18}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE:-0.60}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2:-3.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO:-0.35}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF:-0.25}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE:-0.35}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE:-0.45}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE:-0.95}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT:-1.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT:-1.0}"
    if [[ "$METHOD" == "d2ma_score_lm_only_v4_precision" ]]; then
      export STSLAM_OBSERVABILITY_LOG=0
      export STSLAM_NEAR_BOUNDARY_DIAGNOSTICS=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP="${LIFECYCLE_DUMP_REQUESTED:-0}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V5_USEFULNESS_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_V5_TRACE_LOG=0
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE=0
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG=0
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN=0
    fi
    if [[ "$METHOD" == "d2ma_lifecycle_v8_precision" ]]; then
      export STSLAM_OBSERVABILITY_LOG=0
      export STSLAM_NEAR_BOUNDARY_DIAGNOSTICS=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT=1
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP="${LIFECYCLE_DUMP_REQUESTED:-0}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V5_USEFULNESS_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_V5_TRACE_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_COVERAGE_AWARE_V7=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_V8=1
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_AGE_KFS="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_AGE_KFS:-2}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MAX_PROBATION_AGE_KFS="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MAX_PROBATION_AGE_KFS:-6}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_POSE_USE="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_POSE_USE:-1}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_WINDOWS="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_WINDOWS:-1}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_EDGES="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_EDGES:-2}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_INLIER_RATE="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_INLIER_RATE:-0.60}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MAX_LBA_MEAN_CHI2="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MAX_LBA_MEAN_CHI2:-15.0}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_OBS_FOR_MATURITY="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_OBS_FOR_MATURITY:-3}"
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE=0
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG=0
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN=0
    fi
    if [[ "$METHOD" == "d2ma_lifecycle_v9_precision" || "$METHOD" == "d2ma_occlusion_aware_v10_precision" || "$METHOD" == "d2ma_recovery_v11_precision" || "$METHOD" == "d2ma_recovery_v12_probation_precision" || "$METHOD" == "d2ma_recovery_v12_fixed_delay_2kf_precision" || "$METHOD" == "d2ma_recovery_v12_fixed_delay_4kf_precision" || "$METHOD" == "d2ma_recovery_v13_pose_chain_guard_precision" ]]; then
      export STSLAM_OBSERVABILITY_LOG=0
      export STSLAM_NEAR_BOUNDARY_DIAGNOSTICS=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT=1
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP="${LIFECYCLE_DUMP_REQUESTED:-0}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V5_USEFULNESS_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_V5_TRACE_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_COVERAGE_AWARE_V7=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_V8=1
      export STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9=1
      export STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9_MIN_AGE_KFS="${STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9_MIN_AGE_KFS:-2}"
      if [[ "$METHOD" == "d2ma_occlusion_aware_v10_precision" || "$METHOD" == "d2ma_recovery_v11_precision" || "$METHOD" == "d2ma_recovery_v12_probation_precision" || "$METHOD" == "d2ma_recovery_v12_fixed_delay_2kf_precision" || "$METHOD" == "d2ma_recovery_v12_fixed_delay_4kf_precision" || "$METHOD" == "d2ma_recovery_v13_pose_chain_guard_precision" ]]; then
        export STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9_MIN_POSE_USE="${STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9_MIN_POSE_USE:-1}"
      else
        export STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9_MIN_POSE_USE="${STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9_MIN_POSE_USE:-2}"
      fi
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_AGE_KFS="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_AGE_KFS:-2}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MAX_PROBATION_AGE_KFS="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MAX_PROBATION_AGE_KFS:-6}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_POSE_USE="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_POSE_USE:-1}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_WINDOWS="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_WINDOWS:-1}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_EDGES="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_EDGES:-2}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_INLIER_RATE="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_INLIER_RATE:-0.60}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MAX_LBA_MEAN_CHI2="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MAX_LBA_MEAN_CHI2:-15.0}"
      export STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_OBS_FOR_MATURITY="${STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_OBS_FOR_MATURITY:-3}"
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE=0
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG=0
      export STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN=0
      if [[ "$METHOD" == "d2ma_occlusion_aware_v10_precision" ]]; then
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_AWARE=1
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_AWARE_LBA_DELAY=1
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MAX_KEYFRAME_GAP="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MAX_KEYFRAME_GAP:-2}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_BOUNDARY_FEATURES="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_BOUNDARY_FEATURES:-60}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_DYNAMIC_FEATURES="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_DYNAMIC_FEATURES:-80}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_SUPPORT_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_SUPPORT_SCORE:-0.55}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_CANDIDATE_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_CANDIDATE_SCORE:-0.50}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_TOTAL_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_TOTAL_SCORE:-1.05}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MAX_PROMOTIONS_PER_KEYFRAME="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MAX_PROMOTIONS_PER_KEYFRAME:-8}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MAX_PROMOTIONS_PER_NEIGHBOR="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MAX_PROMOTIONS_PER_NEIGHBOR:-2}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_LBA_DELAY_MIN_AGE_KFS="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_LBA_DELAY_MIN_AGE_KFS:-3}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_LBA_DELAY_MIN_POSE_USE="${STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_LBA_DELAY_MIN_POSE_USE:-2}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_LOG="${OCCLUSION_LOG_REQUESTED:-0}"
      fi
      if [[ "$METHOD" == "d2ma_recovery_v11_precision" || "$METHOD" == "d2ma_recovery_v12_probation_precision" || "$METHOD" == "d2ma_recovery_v12_fixed_delay_2kf_precision" || "$METHOD" == "d2ma_recovery_v12_fixed_delay_4kf_precision" || "$METHOD" == "d2ma_recovery_v13_pose_chain_guard_precision" ]]; then
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11=1
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_LOG="${RECOVERY_V11_LOG_REQUESTED:-0}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_EARLY_LBA="${RECOVERY_V11_EARLY_LBA_REQUESTED:-1}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_NEED_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_NEED_SCORE:-1.0}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_SUPPORT_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_SUPPORT_SCORE:-0.70}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_RELIABLE_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_RELIABLE_SUPPORT:-2}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_DEPTH_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_DEPTH_SUPPORT:-1}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_RESIDUAL_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_RESIDUAL_SUPPORT:-1}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_CANDIDATE_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_CANDIDATE_SCORE:-0.70}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_TOTAL_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_TOTAL_SCORE:-1.45}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MAX_PROMOTIONS_PER_KEYFRAME="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MAX_PROMOTIONS_PER_KEYFRAME:-12}"
        export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MAX_PROMOTIONS_PER_NEIGHBOR="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MAX_PROMOTIONS_PER_NEIGHBOR:-3}"
        if [[ "$METHOD" == "d2ma_recovery_v12_probation_precision" || "$METHOD" == "d2ma_recovery_v12_fixed_delay_2kf_precision" || "$METHOD" == "d2ma_recovery_v12_fixed_delay_4kf_precision" || "$METHOD" == "d2ma_recovery_v13_pose_chain_guard_precision" ]]; then
          export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_EARLY_LBA=0
          export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_PROBATION=1
          export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MODE=posterior
          export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_AGE_KFS="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_AGE_KFS:-2}"
          export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MAX_PROBATION_AGE_KFS="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MAX_PROBATION_AGE_KFS:-8}"
          export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_POSE_USE="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_POSE_USE:-3}"
          export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_OBSERVATIONS="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_OBSERVATIONS:-4}"
          export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_FOUND_RATIO="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_FOUND_RATIO:-0.35}"
          export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_INLIER_RATE="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_INLIER_RATE:-0.60}"
          export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MAX_MEAN_CHI2="${STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MAX_MEAN_CHI2:-6.0}"
          if [[ "$METHOD" == "d2ma_recovery_v12_fixed_delay_2kf_precision" ]]; then
            export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MODE=fixed_delay
            export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_FIXED_DELAY_KFS=2
          elif [[ "$METHOD" == "d2ma_recovery_v12_fixed_delay_4kf_precision" ]]; then
            export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MODE=fixed_delay
            export STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_FIXED_DELAY_KFS=4
          fi
        fi
        if [[ "$METHOD" == "d2ma_recovery_v13_pose_chain_guard_precision" ]]; then
          export STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13=1
          export STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_LOG="${POSE_CHAIN_GUARD_V13_LOG_REQUESTED:-0}"
          export STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_MIN_NEED_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_MIN_NEED_SCORE:-2.0}"
          export STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_REQUIRE_KEYFRAME_PRESSURE="${STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_REQUIRE_KEYFRAME_PRESSURE:-1}"
          export STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_REQUIRE_SCALE_OR_LBA_PRESSURE="${STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_REQUIRE_SCALE_OR_LBA_PRESSURE:-1}"
        fi
      fi
    fi
    ;;
  d2ma_score_lm_only_v5)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX="${STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX:-5}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX:-18}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE:-0.60}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2:-3.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO:-0.35}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF:-0.25}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE:-0.35}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE:-0.45}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE:-0.95}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT:-1.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT:-1.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V5_USEFULNESS_LOG=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_V5_TRACE_LOG="${STSLAM_DYNAMIC_MAP_ADMISSION_V5_TRACE_LOG:-0}"
    ;;
  d2ma_state_aware_lm_only_v6)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX="${STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX:-5}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX:-18}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE:-0.60}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2:-3.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO:-0.35}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF:-0.25}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE:-0.35}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE:-0.45}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE:-0.95}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT:-1.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT:-1.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_AWARE=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_TRACKING_INLIERS="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_TRACKING_INLIERS:-160}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MAX_KEYFRAME_GAP="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MAX_KEYFRAME_GAP:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_STEP_RATIO="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_STEP_RATIO:-1.60}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_KEYFRAME_STEP="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_KEYFRAME_STEP:-0.030}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_LBA_EDGES_PER_MP="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_LBA_EDGES_PER_MP:-1.60}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_NEED_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_NEED_SCORE:-1.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_KF_STEP_EWMA_ALPHA="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_KF_STEP_EWMA_ALPHA:-0.20}"
    ;;
  d2ma_coverage_aware_lm_only_v7|d2ma_coverage_aware_lm_only_v7_plain|d2ma_coverage_aware_lm_only_v7_shadow)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME=0
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX="${STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX:-5}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX:-18}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS="${STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE:-0.60}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2:-3.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO:-0.35}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF="${STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF:-0.25}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE:-0.35}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE:-0.45}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE:-0.95}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT:-1.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT="${STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT:-1.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_AWARE=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_TRACKING_INLIERS="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_TRACKING_INLIERS:-160}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MAX_KEYFRAME_GAP="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MAX_KEYFRAME_GAP:-2}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_STEP_RATIO="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_STEP_RATIO:-1.60}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_KEYFRAME_STEP="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_KEYFRAME_STEP:-0.030}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_LBA_EDGES_PER_MP="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_LBA_EDGES_PER_MP:-1.60}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_NEED_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_NEED_SCORE:-1.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_STATE_KF_STEP_EWMA_ALPHA="${STSLAM_DYNAMIC_MAP_ADMISSION_STATE_KF_STEP_EWMA_ALPHA:-0.20}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_COVERAGE_AWARE_V7=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_MIN_UNMATCHED_BOUNDARY_FEATURES="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_MIN_UNMATCHED_BOUNDARY_FEATURES:-40}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_MIN_UNMATCHED_BOUNDARY_CELLS="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_MIN_UNMATCHED_BOUNDARY_CELLS:-4}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_GRID_COLS="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_GRID_COLS:-4}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_GRID_ROWS="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_GRID_ROWS:-3}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_MIN_NEED_SCORE="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_MIN_NEED_SCORE:-1.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_MAX_PROMOTIONS_PER_KEYFRAME="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_MAX_PROMOTIONS_PER_KEYFRAME:-24}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_MAX_PROMOTIONS_PER_NEIGHBOR="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_MAX_PROMOTIONS_PER_NEIGHBOR:-4}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MIN_AGE_KFS="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MIN_AGE_KFS:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MIN_POSE_USE="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MIN_POSE_USE:-1}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MIN_INLIER_RATE="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MIN_INLIER_RATE:-0.55}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MAX_MEAN_CHI2="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MAX_MEAN_CHI2:-25.0}"
    export STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_LOW_USE_AGE_KFS="${STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_LOW_USE_AGE_KFS:-3}"
    if [[ "$METHOD" == "d2ma_coverage_aware_lm_only_v7_shadow" ]]; then
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT=1
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP=1
    elif [[ "$METHOD" == "d2ma_coverage_aware_lm_only_v7_plain" ]]; then
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG=0
      export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP=0
    else
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT=1
      export STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG=1
      export STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP=1
    fi
    ;;
  samecount_nonboundary_r5)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    ;;
  matched_nonboundary_r5)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    export STSLAM_DYNAMIC_MAP_ADMISSION_MATCHED_CONTROL_GRID_COLS=4
    export STSLAM_DYNAMIC_MAP_ADMISSION_MATCHED_CONTROL_GRID_ROWS=3
    ;;
  *)
    echo "Unknown METHOD: $METHOD" >&2
    exit 2
    ;;
esac

mkdir -p "$OUT_DIR"
{
  echo "d2ma_sidechannel_isolation_protocol=1"
  echo "d2ma_method=$METHOD"
  echo "d2ma_required_note=mask_sidechannel_only_no_rgb_depth_pose_frontend_paths"
} > "$OUT_DIR/d2ma_protocol_manifest.txt"

bash "$ROOT/scripts/run_backend_rgbd.sh" "$DATASET_ID" "$PROFILE" "$OUT_DIR"

python3 "$ROOT/tools/validate_d2ma_sidechannel_protocol.py" \
  --run-dir "$OUT_DIR" \
  --method "$METHOD" \
  --write-json "$OUT_DIR/d2ma_protocol_validation.json"
