#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ $# -lt 3 ]]; then
  cat >&2 <<'EOF'
Usage:
  scripts/run_d2ma_sidechannel_isolated.sh DATASET_ID METHOD OUT_DIR [PROFILE]

METHOD:
  raw
  d2ma_min
  d2ma_b_r5
  samecount_nonboundary_r5

This wrapper enforces the D2MA side-channel isolation protocol:
  - masks are passed only as map-admission provenance side-channel
  - RGB/depth are not image-level filtered by ORB-SLAM3 mask mode
  - dynamic feature deletion, depth invalidation, and pose-level panoptic paths are disabled
EOF
  exit 2
fi

DATASET_ID="$1"
METHOD="$2"
OUT_DIR="$3"
PROFILE="${4:-hybrid_sequential_semantic_only}"

export DSLAM_CPUSET="${DSLAM_CPUSET:-0}"

export ORB_SLAM3_MASK_MODE=off
export STSLAM_PANOPTIC_SIDE_CHANNEL_ONLY=1
export STSLAM_FORCE_FILTER_DETECTED_DYNAMIC_FEATURES=0
export STSLAM_FORCE_FILTER_DETECTED_DYNAMIC_FEATURE_STAGES=none
export STSLAM_RGBD_DYNAMIC_FRONTEND_SPLIT=0
export STSLAM_SEMANTIC_GEOMETRIC_VERIFICATION=0
export STSLAM_SEMANTIC_CANDIDATE_GEOMETRY_GATE=0
export STSLAM_SEMANTIC_CANDIDATE_SPARSE_FLOW_GATE=0
export STSLAM_SEMANTIC_CONSERVATIVE_DYNAMIC_DELETE=0
export STSLAM_SEMANTIC_STRICT_STATIC_KEEP=0
export STSLAM_GEOMETRIC_DYNAMIC_REJECTION=0
export STSLAM_DYNAMIC_DEPTH_INVALIDATION=0
export STSLAM_OBSERVABILITY_LOG=1

export STSLAM_DYNAMIC_MAP_ADMISSION_VETO=0
export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_STEREO_INITIALIZATION=0
export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_NEED_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0

export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_DIAGNOSTICS=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0

export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_CREATE_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0

export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY=0
export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME=0
export STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=0

case "$METHOD" in
  raw)
    ;;
  d2ma_min)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    ;;
  d2ma_b_r5)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    ;;
  samecount_nonboundary_r5)
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_CREATE_NEW_KEYFRAME=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS=1
    export STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX=5
    ;;
  *)
    echo "Unknown METHOD: $METHOD" >&2
    exit 2
    ;;
esac

mkdir -p "$OUT_DIR"
{
  echo "d2ma_sidechannel_isolation_protocol=1"
  echo "d2ma_method=$METHOD"
  echo "d2ma_required_note=mask_sidechannel_only_no_rgb_depth_pose_frontend_paths"
} > "$OUT_DIR/d2ma_protocol_manifest.txt"

bash "$ROOT/scripts/run_backend_rgbd.sh" "$DATASET_ID" "$PROFILE" "$OUT_DIR"

python3 "$ROOT/tools/validate_d2ma_sidechannel_protocol.py" \
  --run-dir "$OUT_DIR" \
  --method "$METHOD" \
  --write-json "$OUT_DIR/d2ma_protocol_validation.json"
