#!/usr/bin/env python3
"""Validate that a backend run used the D2MA side-channel isolation protocol."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List


ANY_VALUE = "__ANY__"


BASE_REQUIRED = {
    "ORB_SLAM3_MASK_MODE": "off",
    "STSLAM_PANOPTIC_SIDE_CHANNEL_ONLY": "1",
    "STSLAM_FORCE_FILTER_DETECTED_DYNAMIC_FEATURES": "0",
    "STSLAM_FORCE_FILTER_DETECTED_DYNAMIC_FEATURE_STAGES": "none",
    "STSLAM_RGBD_DYNAMIC_FRONTEND_SPLIT": "0",
    "STSLAM_SEMANTIC_GEOMETRIC_VERIFICATION": "0",
    "STSLAM_SEMANTIC_CANDIDATE_GEOMETRY_GATE": "0",
    "STSLAM_SEMANTIC_CANDIDATE_SPARSE_FLOW_GATE": "0",
    "STSLAM_SEMANTIC_CONSERVATIVE_DYNAMIC_DELETE": "0",
    "STSLAM_SEMANTIC_STRICT_STATIC_KEEP": "0",
    "STSLAM_GEOMETRIC_DYNAMIC_REJECTION": "0",
    "STSLAM_DYNAMIC_DEPTH_INVALIDATION": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_VETO": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_STEREO_INITIALIZATION": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_NEED_NEW_KEYFRAME": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_AWARE": "0",
    "STSLAM_STATIC_BACKGROUND_POSE_REFINE": "0",
    "STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN": "0",
}


METHOD_REQUIRED = {
    "raw": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
    },
    "d2ma_min": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
    },
    "d2ma_b_r5": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
    },
    "d2ma_b_r5_precision_mainline": {
        "STSLAM_OBSERVABILITY_LOG": "0",
        "STSLAM_NEAR_BOUNDARY_DIAGNOSTICS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP": "0",
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE": "0",
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG": "0",
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN": "0",
    },
    "d2ma_b_r5_static_pose_refine": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE": "1",
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG": "1",
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_MATCHES": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_NEAR_RADIUS_PX": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_TRANSLATION_M": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_ROTATION_DEG": ANY_VALUE,
    },
    "d2ma_b_r5_static_pose_refine_residual_gate": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE": "1",
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG": "1",
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_MATCHES": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_NEAR_RADIUS_PX": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_TRANSLATION_M": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_ROTATION_DEG": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_TRANSLATION_M": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_ROTATION_DEG": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN": "1",
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_MEAN_CHI2_BEFORE": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_CHI2_GAIN_RATIO": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_CHI2_GAIN_ABS": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MIN_INLIER_RATIO_GAIN": ANY_VALUE,
        "STSLAM_STATIC_BACKGROUND_POSE_REFINE_MAX_MEAN_CHI2_AFTER": ANY_VALUE,
    },
    "d2ma_support_b_r5_s18_m2_o2": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": "18",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": "2",
    },
    "d2ma_supportq_b_r5_s18_m2_o2_q2": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": "18",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": "0.70",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": "3.0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": "0.35",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": "0.25",
    },
    "d2ma_supportq_lm_only_b_r5_s18_m2_o2_q2": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": "18",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": "0.70",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": "3.0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": "0.35",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": "0.25",
    },
    "d2ma_supportq_lm_only_sweep": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": ANY_VALUE,
    },
    "d2ma_score_lm_only_v4": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT": ANY_VALUE,
    },
    "d2ma_score_lm_only_v5": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V5_USEFULNESS_LOG": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_V5_TRACE_LOG": "0",
    },
    "d2ma_state_aware_lm_only_v6": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_AWARE": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_TRACKING_INLIERS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MAX_KEYFRAME_GAP": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_STEP_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_KEYFRAME_STEP": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_LBA_EDGES_PER_MP": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_NEED_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_KF_STEP_EWMA_ALPHA": ANY_VALUE,
    },
    "d2ma_coverage_aware_lm_only_v7": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_AWARE": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_COVERAGE_AWARE_V7": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_MIN_UNMATCHED_BOUNDARY_FEATURES": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_MIN_UNMATCHED_BOUNDARY_CELLS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_GRID_COLS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_GRID_ROWS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_MIN_NEED_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_MAX_PROMOTIONS_PER_KEYFRAME": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_MAX_PROMOTIONS_PER_NEIGHBOR": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MIN_AGE_KFS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MIN_POSE_USE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_MAX_MEAN_CHI2": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION_LOW_USE_AGE_KFS": ANY_VALUE,
    },
    "samecount_nonboundary_r5": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
    },
    "matched_nonboundary_r5": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_MATCHED_CONTROL_GRID_COLS": "4",
        "STSLAM_DYNAMIC_MAP_ADMISSION_MATCHED_CONTROL_GRID_ROWS": "3",
    },
}


PRECISION_SAFE_OVERRIDES = {
    "STSLAM_OBSERVABILITY_LOG": "0",
    "STSLAM_NEAR_BOUNDARY_DIAGNOSTICS": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_V5_USEFULNESS_LOG": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_V5_TRACE_LOG": "0",
    "STSLAM_STATIC_BACKGROUND_POSE_REFINE": "0",
    "STSLAM_STATIC_BACKGROUND_POSE_REFINE_LOG": "0",
    "STSLAM_STATIC_BACKGROUND_POSE_REFINE_REQUIRE_RESIDUAL_GAIN": "0",
}

METHOD_REQUIRED["d2ma_supportq_lm_only_b_r5_s18_m2_o2_q2_precision"] = dict(
    METHOD_REQUIRED["d2ma_supportq_lm_only_b_r5_s18_m2_o2_q2"]
)
METHOD_REQUIRED["d2ma_supportq_lm_only_b_r5_s18_m2_o2_q2_precision"].update(
    PRECISION_SAFE_OVERRIDES
)

METHOD_REQUIRED["d2ma_score_lm_only_v4_precision"] = dict(
    METHOD_REQUIRED["d2ma_score_lm_only_v4"]
)
METHOD_REQUIRED["d2ma_score_lm_only_v4_precision"].update(PRECISION_SAFE_OVERRIDES)

METHOD_REQUIRED["d2ma_lifecycle_v8_precision"] = dict(
    METHOD_REQUIRED["d2ma_score_lm_only_v4"]
)
METHOD_REQUIRED["d2ma_lifecycle_v8_precision"].update(PRECISION_SAFE_OVERRIDES)
METHOD_REQUIRED["d2ma_lifecycle_v8_precision"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_COVERAGE_AWARE_V7": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_V7_PROBATION": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_V8": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_AGE_KFS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V8_MAX_PROBATION_AGE_KFS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_POSE_USE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_WINDOWS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_EDGES": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_LBA_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V8_MAX_LBA_MEAN_CHI2": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V8_MIN_OBS_FOR_MATURITY": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_lifecycle_v9_precision"] = dict(
    METHOD_REQUIRED["d2ma_lifecycle_v8_precision"]
)
METHOD_REQUIRED["d2ma_lifecycle_v9_precision"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9_MIN_AGE_KFS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_LBA_DELAY_V9_MIN_POSE_USE": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_occlusion_aware_v10_precision"] = dict(
    METHOD_REQUIRED["d2ma_lifecycle_v9_precision"]
)
METHOD_REQUIRED["d2ma_occlusion_aware_v10_precision"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_AWARE": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_AWARE_LBA_DELAY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MAX_KEYFRAME_GAP": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_BOUNDARY_FEATURES": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_DYNAMIC_FEATURES": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_CANDIDATE_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MIN_TOTAL_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MAX_PROMOTIONS_PER_KEYFRAME": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_MAX_PROMOTIONS_PER_NEIGHBOR": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_LBA_DELAY_MIN_AGE_KFS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_LBA_DELAY_MIN_POSE_USE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_OCCLUSION_LOG": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v11_precision"] = dict(
    METHOD_REQUIRED["d2ma_lifecycle_v9_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v11_precision"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_LOG": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_EARLY_LBA": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_NEED_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_RESIDUAL_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_CANDIDATE_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MIN_TOTAL_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MAX_PROMOTIONS_PER_KEYFRAME": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_MAX_PROMOTIONS_PER_NEIGHBOR": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v12_probation_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v11_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v12_probation_precision"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V11_EARLY_LBA": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_PROBATION": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MODE": "posterior",
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_AGE_KFS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MAX_PROBATION_AGE_KFS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_POSE_USE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_OBSERVATIONS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_FOUND_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MAX_MEAN_CHI2": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v12_fixed_delay_2kf_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v12_probation_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v12_fixed_delay_2kf_precision"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MODE": "fixed_delay",
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_FIXED_DELAY_KFS": "2",
    }
)

METHOD_REQUIRED["d2ma_recovery_v12_fixed_delay_4kf_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v12_probation_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v12_fixed_delay_4kf_precision"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_MODE": "fixed_delay",
        "STSLAM_DYNAMIC_MAP_ADMISSION_RECOVERY_V12_FIXED_DELAY_KFS": "4",
    }
)

METHOD_REQUIRED["d2ma_recovery_v13_pose_chain_guard_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v12_probation_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v13_pose_chain_guard_precision"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_LOG": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_MIN_NEED_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_REQUIRE_KEYFRAME_PRESSURE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_REQUIRE_SCALE_OR_LBA_PRESSURE": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v14_pose_chain_log_only"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v12_probation_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v14_pose_chain_log_only"].update(
    {
        "STSLAM_OBSERVABILITY_LOG": "1",
        "STSLAM_POSE_CHAIN_QUALITY_LOG": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_LOG": "0",
        "STSLAM_POSE_CHAIN_QUALITY_RECENT_WINDOW": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_STATIC_INLIERS": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_STATIC_GRID_COVERAGE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_STEP_RATIO_THRESHOLD": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_STEP_FOR_MOTION_PRESSURE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_BOUNDARY_INLIER_FRAC_THRESHOLD": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_RECENT_KEYFRAMES": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_KEYFRAME_RATE_THRESHOLD": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_KEYFRAMES_PER_METER_THRESHOLD": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v15_relaxed_pose_chain_guard_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v12_probation_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v15_relaxed_pose_chain_guard_precision"].update(
    {
        "STSLAM_OBSERVABILITY_LOG": "1",
        "STSLAM_POSE_CHAIN_QUALITY_LOG": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_LOG": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_LOG": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_MIN_NEED_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_STEP_RATIO_THRESHOLD": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_REQUIRE_KEYFRAME_PRESSURE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_MIN_RESIDUAL_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_MAX_PROMOTIONS_PER_KEYFRAME": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_MAX_PROMOTIONS_PER_NEIGHBOR": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_RECENT_WINDOW": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_STATIC_INLIERS": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_STATIC_GRID_COVERAGE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_STEP_RATIO_THRESHOLD": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_STEP_FOR_MOTION_PRESSURE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_BOUNDARY_INLIER_FRAC_THRESHOLD": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_RECENT_KEYFRAMES": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_KEYFRAME_RATE_THRESHOLD": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_KEYFRAMES_PER_METER_THRESHOLD": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v16_pose_chain_controller_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v12_probation_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v16_pose_chain_controller_precision"].update(
    {
        "STSLAM_OBSERVABILITY_LOG": "1",
        "STSLAM_POSE_CHAIN_QUALITY_LOG": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V13_LOG": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_POSE_CHAIN_GUARD_V15_LOG": "0",
        "STSLAM_POSE_CHAIN_CONTROLLER_V16": "1",
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_LOG": "1",
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_LBA": "1",
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_ADMISSION": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MIN_STEP_RATIO": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_REQUIRE_KEYFRAME_PRESSURE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_REQUIRE_SUPPORT_LOW": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_REQUIRE_BOUNDARY_PRESSURE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MIN_RESIDUAL_SUPPORT": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MAX_PROMOTIONS_PER_KEYFRAME": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MAX_PROMOTIONS_PER_NEIGHBOR": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MIN_AGE_KFS": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MIN_POSE_USE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MIN_OBSERVATIONS": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MIN_FOUND_RATIO": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_CONTROLLER_V16_MAX_MEAN_CHI2": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_RECENT_WINDOW": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_STATIC_INLIERS": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_STATIC_GRID_COVERAGE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_STEP_RATIO_THRESHOLD": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_STEP_FOR_MOTION_PRESSURE": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_BOUNDARY_INLIER_FRAC_THRESHOLD": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_MIN_RECENT_KEYFRAMES": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_KEYFRAME_RATE_THRESHOLD": ANY_VALUE,
        "STSLAM_POSE_CHAIN_QUALITY_KEYFRAMES_PER_METER_THRESHOLD": ANY_VALUE,
    }
)


METHOD_REQUIRED["d2ma_recovery_v17_support_low_fallback_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v16_pose_chain_controller_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v17_support_low_fallback_precision"].update(
    {
        "STSLAM_SUPPORT_LOW_FALLBACK_V17": "1",
        "STSLAM_SUPPORT_LOW_FALLBACK_V17_LOG": "1",
        "STSLAM_SUPPORT_LOW_FALLBACK_V17_REQUIRE_KEYFRAME_PRESSURE": ANY_VALUE,
        "STSLAM_SUPPORT_LOW_FALLBACK_V17_ALLOW_RISK": ANY_VALUE,
        "STSLAM_SUPPORT_LOW_FALLBACK_V17_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_SUPPORT_LOW_FALLBACK_V17_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_SUPPORT_LOW_FALLBACK_V17_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_SUPPORT_LOW_FALLBACK_V17_MIN_RESIDUAL_SUPPORT": ANY_VALUE,
        "STSLAM_SUPPORT_LOW_FALLBACK_V17_MAX_PROMOTIONS_PER_KEYFRAME": ANY_VALUE,
        "STSLAM_SUPPORT_LOW_FALLBACK_V17_MAX_PROMOTIONS_PER_NEIGHBOR": ANY_VALUE,
        "STSLAM_KEYFRAME_OBSERVABILITY_GAIN_V17": "1",
        "STSLAM_KEYFRAME_OBSERVABILITY_GAIN_V17_MAX_POINT_BOOST": ANY_VALUE,
        "STSLAM_KEYFRAME_OBSERVABILITY_GAIN_V17_ALLOW_RISK": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v17_support_low_fallback_only_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v17_support_low_fallback_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v17_support_low_fallback_only_precision"].update(
    {
        "STSLAM_KEYFRAME_OBSERVABILITY_GAIN_V17": "0",
    }
)

METHOD_REQUIRED["d2ma_recovery_v17_keyframe_observability_only_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v17_support_low_fallback_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v17_keyframe_observability_only_precision"].update(
    {
        "STSLAM_SUPPORT_LOW_FALLBACK_V17": "0",
        "STSLAM_SUPPORT_LOW_FALLBACK_V17_LOG": "0",
    }
)

METHOD_REQUIRED["d2ma_recovery_v18_pose_step_safeguard_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v17_support_low_fallback_only_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v18_pose_step_safeguard_precision"].update(
    {
        "STSLAM_POSE_STEP_SAFEGUARD_V18": "1",
        "STSLAM_POSE_STEP_SAFEGUARD_V18_LOG": "1",
        "STSLAM_POSE_STEP_SAFEGUARD_V18_MAX_STEP_RATIO": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V18_MAX_ABS_STEP_M": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V18_MIN_RECENT_STEPS": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V18_REQUIRE_SUPPORT_LOW": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V18_REQUIRE_KEYFRAME_PRESSURE": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V18_REQUIRE_MOTION_PRESSURE": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v19_pose_step_donoharm_grid_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v18_pose_step_safeguard_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v19_pose_step_donoharm_grid_precision"].update(
    {
        "STSLAM_POSE_STEP_SAFEGUARD_V19_DO_NO_HARM": "1",
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MAX_TRIGGER_STEP_RATIO": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MAX_ESTIMATED_STEP_M": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MIN_STATIC_INLIERS_FOR_EXTREME": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MAX_STATIC_GRID_COVERAGE_FOR_EXTREME": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_CLAMP_BLEND": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v20_cluster_verified_pose_step_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v18_pose_step_safeguard_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v20_cluster_verified_pose_step_precision"].update(
    {
        "STSLAM_POSE_STEP_SAFEGUARD_V19_DO_NO_HARM": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MAX_TRIGGER_STEP_RATIO": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MAX_ESTIMATED_STEP_M": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MIN_STATIC_INLIERS_FOR_EXTREME": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MAX_STATIC_GRID_COVERAGE_FOR_EXTREME": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_CLAMP_BLEND": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V20_CLUSTER_VERIFICATION": "1",
        "STSLAM_POSE_STEP_SAFEGUARD_V20_CLUSTER_WINDOW_FRAMES": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V20_MIN_CLUSTER_HITS": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v21_residual_verified_pose_step_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v18_pose_step_safeguard_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v21_residual_verified_pose_step_precision"].update(
    {
        "STSLAM_POSE_STEP_SAFEGUARD_V19_DO_NO_HARM": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MAX_TRIGGER_STEP_RATIO": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MAX_ESTIMATED_STEP_M": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MIN_STATIC_INLIERS_FOR_EXTREME": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_MAX_STATIC_GRID_COVERAGE_FOR_EXTREME": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V19_CLAMP_BLEND": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V20_CLUSTER_VERIFICATION": "0",
        "STSLAM_POSE_STEP_SAFEGUARD_V21_RESIDUAL_VERIFICATION": "1",
        "STSLAM_POSE_STEP_SAFEGUARD_V21_STATIC_NEAR_RADIUS_PX": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V21_MIN_RESIDUAL_OBS": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V21_MAX_CHI2_INFLATION_RATIO": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V21_MAX_CHI2_INCREASE_ABS": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V21_MAX_INLIER_RATIO_DROP": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V21_REJECT_INVALID_RESIDUALS": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v22_contextual_residual_pose_step_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v21_residual_verified_pose_step_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v22_contextual_residual_pose_step_precision"].update(
    {
        "STSLAM_POSE_STEP_SAFEGUARD_V22_CONTEXTUAL_RESIDUAL_GATE": "1",
        "STSLAM_POSE_STEP_SAFEGUARD_V22_MIN_DYNAMIC_FEATURE_GRID_COVERAGE": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V22_MAX_HAZARD_STATIC_INLIERS": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V22_MAX_HAZARD_STATIC_GRID_COVERAGE": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V22_MIN_HAZARD_CHI2_INCREASE_ABS": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V22_MIN_HAZARD_INLIER_RATIO_DROP": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V22_REQUIRE_MOTION_PRESSURE": ANY_VALUE,
    }
)

METHOD_REQUIRED["d2ma_recovery_v23_segment_residual_pose_step_precision"] = dict(
    METHOD_REQUIRED["d2ma_recovery_v22_contextual_residual_pose_step_precision"]
)
METHOD_REQUIRED["d2ma_recovery_v23_segment_residual_pose_step_precision"].update(
    {
        "STSLAM_POSE_STEP_SAFEGUARD_V23_SEGMENT_RESIDUAL_CONTROLLER": "1",
        "STSLAM_POSE_STEP_SAFEGUARD_V23_SEGMENT_WINDOW_FRAMES": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V23_MIN_SEGMENT_HITS": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V23_HOLD_FRAMES": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V23_MIN_DYNAMIC_FEATURE_GRID_COVERAGE": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V23_MAX_SEGMENT_STATIC_INLIERS": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V23_MAX_SEGMENT_STATIC_GRID_COVERAGE": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V23_MIN_SEGMENT_CHI2_INCREASE_ABS": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V23_MIN_SEGMENT_INLIER_RATIO_DROP": ANY_VALUE,
        "STSLAM_POSE_STEP_SAFEGUARD_V23_REQUIRE_MOTION_PRESSURE": ANY_VALUE,
    }
)


METHOD_REQUIRED["d2ma_coverage_aware_lm_only_v7"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP": "1",
    }
)

METHOD_REQUIRED["d2ma_coverage_aware_lm_only_v7_plain"] = dict(
    METHOD_REQUIRED["d2ma_coverage_aware_lm_only_v7"]
)
METHOD_REQUIRED["d2ma_coverage_aware_lm_only_v7_plain"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP": "0",
    }
)

METHOD_REQUIRED["d2ma_coverage_aware_lm_only_v7_shadow"] = dict(
    METHOD_REQUIRED["d2ma_coverage_aware_lm_only_v7"]
)
METHOD_REQUIRED["d2ma_coverage_aware_lm_only_v7_shadow"].update(
    {
        "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_COLLECT": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_CONSTRAINT_ROLE_LOG": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_LIFECYCLE_DUMP": "1",
    }
)


def parse_key_values(path: Path) -> Dict[str, str]:
    values: Dict[str, str] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key] = value
    return values


def validate(manifest: Dict[str, str], method: str) -> Dict[str, object]:
    if method not in METHOD_REQUIRED:
        raise SystemExit(f"Unknown method: {method}")

    required = dict(BASE_REQUIRED)
    required.update(METHOD_REQUIRED[method])

    errors: List[Dict[str, str]] = []
    for key, expected in required.items():
        actual = manifest.get(key)
        if (
            actual is None
            and key == "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY"
            and expected == "0"
        ):
            actual = "0"
        if expected == ANY_VALUE:
            if actual is None or actual == "":
                errors.append({"key": key, "expected": "present", "actual": "" if actual is None else actual})
            continue
        if actual != expected:
            errors.append({"key": key, "expected": expected, "actual": "" if actual is None else actual})

    return {
        "valid": not errors,
        "method": method,
        "errors": errors,
        "checked_keys": sorted(required),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--method", choices=sorted(METHOD_REQUIRED), required=True)
    parser.add_argument("--write-json", type=Path)
    args = parser.parse_args()

    manifest_path = args.run_dir / "run_manifest.txt"
    if not manifest_path.exists():
        raise SystemExit(f"Missing run manifest: {manifest_path}")

    payload = validate(parse_key_values(manifest_path), args.method)
    payload["run_dir"] = str(args.run_dir)
    payload["manifest"] = str(manifest_path)

    text = json.dumps(payload, ensure_ascii=False, indent=2)
    print(text)
    if args.write_json:
        args.write_json.write_text(text + "\n", encoding="utf-8")

    if not payload["valid"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
