#!/usr/bin/env python3
"""Validate that a backend run used the D2MA side-channel isolation protocol."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List


ANY_VALUE = "__ANY__"


BASE_REQUIRED = {
    "ORB_SLAM3_MASK_MODE": "off",
    "STSLAM_PANOPTIC_SIDE_CHANNEL_ONLY": "1",
    "STSLAM_FORCE_FILTER_DETECTED_DYNAMIC_FEATURES": "0",
    "STSLAM_FORCE_FILTER_DETECTED_DYNAMIC_FEATURE_STAGES": "none",
    "STSLAM_RGBD_DYNAMIC_FRONTEND_SPLIT": "0",
    "STSLAM_SEMANTIC_GEOMETRIC_VERIFICATION": "0",
    "STSLAM_SEMANTIC_CANDIDATE_GEOMETRY_GATE": "0",
    "STSLAM_SEMANTIC_CANDIDATE_SPARSE_FLOW_GATE": "0",
    "STSLAM_SEMANTIC_CONSERVATIVE_DYNAMIC_DELETE": "0",
    "STSLAM_SEMANTIC_STRICT_STATIC_KEEP": "0",
    "STSLAM_GEOMETRIC_DYNAMIC_REJECTION": "0",
    "STSLAM_DYNAMIC_DEPTH_INVALIDATION": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_VETO": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_STEREO_INITIALIZATION": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_NEED_NEW_KEYFRAME": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "0",
    "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_AWARE": "0",
}


METHOD_REQUIRED = {
    "raw": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
    },
    "d2ma_min": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
    },
    "d2ma_b_r5": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
    },
    "d2ma_support_b_r5_s18_m2_o2": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": "18",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": "2",
    },
    "d2ma_supportq_b_r5_s18_m2_o2_q2": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": "18",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": "0.70",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": "3.0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": "0.35",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": "0.25",
    },
    "d2ma_supportq_lm_only_b_r5_s18_m2_o2_q2": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": "18",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": "0.70",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": "3.0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": "0.35",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": "2",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": "0.25",
    },
    "d2ma_supportq_lm_only_sweep": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": ANY_VALUE,
    },
    "d2ma_score_lm_only_v4": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT": ANY_VALUE,
    },
    "d2ma_score_lm_only_v5": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_V5_USEFULNESS_LOG": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_V5_TRACE_LOG": "0",
    },
    "d2ma_state_aware_lm_only_v6": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_CREATE_NEW_KEYFRAME": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_SUPPORT_RADIUS_PX": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_DELAYED_BOUNDARY_MIN_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RELIABLE_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_DEPTH_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_RESIDUAL_OBS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_INLIER_RATE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_MEAN_CHI2": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FOUND_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MIN_FRAME_SPAN": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY_MAX_DEPTH_REL_DIFF": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_BASED": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_RAW_SUPPORT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_SUPPORT_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_CANDIDATE_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_MIN_TOTAL_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_SUPPORT_WEIGHT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_SCORE_CANDIDATE_WEIGHT": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_AWARE": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_TRACKING_INLIERS": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MAX_KEYFRAME_GAP": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_STEP_RATIO": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_KEYFRAME_STEP": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_LBA_EDGES_PER_MP": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_MIN_NEED_SCORE": ANY_VALUE,
        "STSLAM_DYNAMIC_MAP_ADMISSION_STATE_KF_STEP_EWMA_ALPHA": ANY_VALUE,
    },
    "samecount_nonboundary_r5": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "0",
    },
    "matched_nonboundary_r5": {
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_VETO_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_VETO": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_SAME_COUNT_CONTROL": "0",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL_CREATE_NEW_KEYFRAME": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_MATCHED_CONTROL_LOCAL_MAPPING_CREATE_NEW_MAPPOINTS": "1",
        "STSLAM_DYNAMIC_MAP_ADMISSION_BOUNDARY_RADIUS_PX": "5",
        "STSLAM_DYNAMIC_MAP_ADMISSION_MATCHED_CONTROL_GRID_COLS": "4",
        "STSLAM_DYNAMIC_MAP_ADMISSION_MATCHED_CONTROL_GRID_ROWS": "3",
    },
}


def parse_key_values(path: Path) -> Dict[str, str]:
    values: Dict[str, str] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key] = value
    return values


def validate(manifest: Dict[str, str], method: str) -> Dict[str, object]:
    if method not in METHOD_REQUIRED:
        raise SystemExit(f"Unknown method: {method}")

    required = dict(BASE_REQUIRED)
    required.update(METHOD_REQUIRED[method])

    errors: List[Dict[str, str]] = []
    for key, expected in required.items():
        actual = manifest.get(key)
        if (
            actual is None
            and key == "STSLAM_DYNAMIC_MAP_ADMISSION_SUPPORT_QUALITY"
            and expected == "0"
        ):
            actual = "0"
        if expected == ANY_VALUE:
            if actual is None or actual == "":
                errors.append({"key": key, "expected": "present", "actual": "" if actual is None else actual})
            continue
        if actual != expected:
            errors.append({"key": key, "expected": expected, "actual": "" if actual is None else actual})

    return {
        "valid": not errors,
        "method": method,
        "errors": errors,
        "checked_keys": sorted(required),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--method", choices=sorted(METHOD_REQUIRED), required=True)
    parser.add_argument("--write-json", type=Path)
    args = parser.parse_args()

    manifest_path = args.run_dir / "run_manifest.txt"
    if not manifest_path.exists():
        raise SystemExit(f"Missing run manifest: {manifest_path}")

    payload = validate(parse_key_values(manifest_path), args.method)
    payload["run_dir"] = str(args.run_dir)
    payload["manifest"] = str(manifest_path)

    text = json.dumps(payload, ensure_ascii=False, indent=2)
    print(text)
    if args.write_json:
        args.write_json.write_text(text + "\n", encoding="utf-8")

    if not payload["valid"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
